Presentation/Protein.Web/Models/ExportModel/ExportType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Protein.Web.Models.ExportModel
{
    public enum ExportType
    {
       Excel = 0,
       Pdf = 1,
       Print = 2
    }
}

Presentation/Protein.Web/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Protein.Data.Export.Model;
using Protein.Common.Extensions;
using Protein.Data.Repositories;
using Protein.Data.Workers;
using Protein.Web.Models.ExportModel;
using Protein.Web.Models.HistoryModel;
using Protein.Web.Models.ImportModel;
using static Protein.Common.Constants.Constants;
using static Protein.Common.Enums.ProteinEnums;
using static Protein.Common.Entities.ProteinEntities;
using Protein.Common.Dto.MediaObjects;
using Protein.Business.Enums.Media;
using Protein.Business.Concrete.Media;
using Protein.Business.Concrete.Responses;
using Protein.Data.Helpers;
using Protein.Common.Constants;
using System.Runtime.Serialization.Formatters.Binary;
using Dapper;
using System.Reflection;
using System.Collections;
using System.Diagnostics;
using Protein.Web.ActionFilter.LoginAttr;
using Protein.Business.Print;

namespace Protein.Web.Controllers
{
    public class CommonController : Controller
    {
        public ActionResult ChangePassword()
        {
            TempData["Alert"] = TempData["Alert"] ?? string.Empty;

            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(FormCollection form)
        {
            dynamic personel = System.Web.HttpContext.Current.Session["Personnel"];

            if (form["newPassword"] != form["newPasswordAgain"])
            {
                TempData["Alert"] = $"swAlert('Uyarı','Şifre Uyumsuzluğu, iki Alanıda Aynı Giriniz!','warning')";
                return View();
            }

            User user = new UserRepository().FindById(long.Parse(Convert.ToString(personel.USER_ID)));
            if (user == null)
            {
                TempData["Alert"] = $"swAlert('Hata','Hatalı E-Posta/Şifre. Lütfen tekrar deneyiniz.','warning')";
                return View();
            }

            user.Password = form["newPassword"].ToMD5().ToUpper();
            SpResponse spResponse = new GenericRepository<User>().Update(user);
            if (spResponse.Code != "100")
            {
                TempData["Alert"] = $"swAlert('Hata','Şifre Değiştirme İşlemi Yapılamadı.','warning')";
                return View();
            }


            TempData["Alert"] = $"swAlert('İşlem Başarılı','Şifre Değiştirme İşlemi Başarıyla Gerçekleştirildi.','success')";

            return RedirectToAction("Index", "Dashboard");
        }
        [HttpPost]
        public virtual ActionResult DownloadByMediaId(long MediaID)
        {
            string handle = Guid.NewGuid().ToString();

            try
            {
                Media media = new GenericRepository<Media>().FindById(MediaID);

                //MemoryStream memStream = new MemoryStream();
                //BinaryFormatter binForm = new BinaryFormatter();
                //memStream.Write(media.FileContent, 0, media.FileContent.Length);
                //memStream.Seek(0, SeekOrigin.Begin);

                //memStream.
                if (media.FileContent != null)
                    TempData[handle] = media.FileContent.ToArray();

                return new JsonResult()
                {
                    Data = new { FileGuid = handle, FileName = media.FileName, IsNull = media.FileContent == null }
                };
            }
            catch (Exception ex) { return new EmptyResult(); }
        }
        [HttpGet]
        public virtual ActionResult Download(string fileGuid, string fileName)
        {
            if (TempData[fileGuid] != null)
            {
                byte[] data = TempData[fileGuid] as byte[];
                TempData[fileGuid] = null;
                return File(data, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
            }
            else
                return new EmptyResult();
        }
        [HttpPost]
        public ActionResult ExportGenerator(Models.ExportModel.ExportVM model)
        {
            ExportResponse response = new ExportResponse();
            if (model.selectedExportColumnValue.Count > 0 || model.IsAllColumns)
            {
                model.ExportType = ExportType.Excel;
           
                model.SetExportColumns();
                response = model.ExportOut();
                if (response.IsDownloaded)
                    TempData[response.Guid] = response.memoryStream.ToArray();
            }
            else
                return new EmptyResult();

            return new JsonResult()
            {
                Data = new { FileGuid = response.Guid, FileName = response.FileName }
            };
        }
        [HttpPost]
        public ActionResult PrintGenerator(string url,string filename)
        {
            if (!url.IsNull() && url!="null")
            {
                byte[] fileBytes = System.IO.File.ReadAllBytes(url);

                TempData[url] = fileBytes;
            }

            return new JsonResult()
            {
                Data = new { FileUrl = url, FileName = filename+".pdf" }
            };
        }
        [HttpGet]
        public JsonResult DeleteMedia(long MediaId, long BaseId, string ObjectType, long ObjectId)
        {

            bool result = new MediaWorker().DeleteMedia(MediaId, ObjectType, BaseId, ObjectId);

            return new JsonResult()
            {
                MaxJsonLength = Int32.MaxValue,
                Data = "OK",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
        [HttpGet]
        public JsonResult FillMedia(long ObjectId, string ObjectType, string DiffrentObjectType = "")
        {
            List<MediaListDto> mediaList = new MediaWorker().FillMedia(ObjectId, ObjectType, DiffrentObjectType);

            return new JsonResult()
            {
                MaxJsonLength = Int32.MaxValue,
                Data = mediaList,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
        [HttpGet]
        public JsonResult HistoryDetail(string Id, string ViewName, string HistoryTitle)
        {
            HistoryVM vm = new HistoryVM();
            if (!string.IsNullOrEmpty(ViewName) && int.Parse(Id) > 0)
            {
                vm.ViewName = ViewName;
                vm.HistoryTitle = HistoryTitle;
                vm.Id = int.Parse(Id);
                vm.GetHistory();
                List<HistoryResponse> response = vm.historyList;
            }
            return Json(vm, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult FillCounty(string cityId)
        {
            object result = null;

            if (!string.IsNullOrEmpty(cityId))
            {
                if (!Extensions.IsInt64(cityId))
                {
                    cityId = new GenericRepository<City>().FindBy($"NAME='{cityId.ToUpper().Trim()}'").FirstOrDefault()?.Id.ToString();
                }
                var CountyList = new CountyRepository().FindBy("TYPE=1 AND CITY_ID=" + cityId);
                result = CountyList.ToJSON();
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GetReason(string claimStatus)
        {
            object result = null;

            if (!string.IsNullOrEmpty(claimStatus))
            {
                var ReasonList = ReasonHelper.GetReasonData("ClaimStatus", claimStatus);

                result = ReasonList.ToJSON();
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult FillCoverage(string coverageIdList)
        {
            object result = null;

            if (!string.IsNullOrEmpty(coverageIdList))
            {
                var CoverageList = new CoverageRepository().FindBy(orderby: "NAME");

                result = CoverageList.ToJSON();
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult FillSagmerCoverageType(string planCoverageId)
        {
            object result = "[]";

            if (planCoverageId.IsInt64())
            {
                V_PlanCoverage v_PlanCoverage = new GenericRepository<V_PlanCoverage>().FindBy($"PLAN_COVERAGE_ID={planCoverageId}", orderby: "").FirstOrDefault();
                if (v_PlanCoverage != null)
                {
                    SagmerCoverageCategory sagmerCategory = new GenericRepository<SagmerCoverageCategory>().FindBy($"BRANCH_ID={v_PlanCoverage.BRANCH_ID} AND COVERAGE_TYPE='{v_PlanCoverage.COVERAGE_TYPE}'").FirstOrDefault();
                    if (sagmerCategory != null)
                    {
                        var sagmerCoverageList = new GenericRepository<SagmerCoverage>().FindBy($"SAGMER_COVERAGE_CATEGORY_ID={sagmerCategory.Id}");

                        List<SagmerCoverageType> sagmerCoverageTypeList = new List<SagmerCoverageType>();

                        string idList = string.Empty;
                        foreach (var sagmerCoverage in sagmerCoverageList)
                        {
                            idList += sagmerCoverage.SagmerCoverageTypeId.ToString() + ", ";
                        }
                        sagmerCoverageTypeList = new GenericRepository<SagmerCoverageType>().FindBy($"ID IN({idList.Substring(0, idList.Length - 2)})");

                        result = sagmerCoverageTypeList.ToJSON();
                    }
                }
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult FillSagmerCoverage(string sagmerTypeId, string planCoverageId)
        {
            object result = null;

            if (sagmerTypeId.IsInt64() && planCoverageId.IsInt64())
            {

Presentation/Protein.Web/Views/Shared/Partials/_Export.cshtml
@model  Protein.Web.Models.ExportModel.ExportVM


@using (Html.BeginForm("ExportGenerator", "Common", FormMethod.Post, new { id = "ExportModal" }))
{
    <div class="modal" id="modalExport" data-noreset="true" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Kolonları seç</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="">
                                @Html.HiddenFor(m => m.ViewName)
                                @Html.HiddenFor(m => m.WhereCondition)
                                @Html.HiddenFor(m=>m.ExportType)
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group has-feedback">
                                            <div class="col-sm-12">
                                                @Html.LabelFor(f => f.IsAllColumns, new { @class = "control-label fl pt-0 mr-10" })
                                                <label class="switch">
                                                    @Html.CheckBoxFor(m => m.IsAllColumns)
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group has-feedback">
                                            <div class="col-sm-12">
                                                @Html.LabelFor(m=>m.ExportColumns, htmlAttributes:
new { @class = "control-label" })

                                                @Html.ListBoxFor(m => m.selectedExportColumnValue,
new MultiSelectList(Model.ExportColumns, "Name", "DisplayName")
, new { @class = "chosen-select" })
                                            </div>
                                        </div>
                                        <div class="btn-wrapper-center">
                                            <button type="button" id="btnExcel" class="btn btn-success btn-sm mr-10">Excel</button>
                                            <button type="button" disabled id="btnPdf" class="btn btn-success btn-sm mr-10">Pdf</button>
                                            <button type="button" disabled id="btnPrint" class="btn btn-success btn-sm mr-10">Print</button>
                                            <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">İptal</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script>
    
    $('#IsAllColumns').change(function () {
        if ($(this).is(":checked")) 
            $('#selectedExportColumnValue').prop('disabled', true).trigger("chosen:updated");
        else 
            $('#selectedExportColumnValue').prop('disabled', false).trigger("chosen:updated");
    });
    $("#btnExcel,#btnPdf").click(function () {
        debugger;
        // Tümü seçilmediğinde ve hiçbir kolon eklenmediğinde...
        if ($('#selectedExportColumnValue').val().length == 0 && $('#IsAllColumns:checkbox:checked').length == 0) {
            alert('Kolon seçmediniz!'); return;
        }
       
        var exportType = this.id.replace('btn', '');
        $('#ExportType').val(exportType);
        debugger;
        var _serialize = $('#ExportModal').serialize();
        
        $.ajax({
            url: '/Common/ExportGenerator',
            type: 'POST',
            data: _serialize,
            dataType: 'json',
            success: function (data) {
                $.unblockUI();
                var response = data;
                window.location = '/Common/Download?fileGuid=' + response.FileGuid
                    + '&filename=' + response.FileName;
            },
            beforeSend: function () {
                $.blockUI({ message: $('#domMessage') });
            },
            complete: function () {
                $.unblockUI();
            }
        });
    });

</script>

Presentation/Protein.Web/Views/Shared/Partials/_History.cshtml
@model Protein.Web.Models.HistoryModel.HistoryVM

<!-- Modal -->
<div class="modal" id="frmHistory_Modal" tabindex="-1" role="dialog" aria-labelledby="frmHistory_ModalLabel">
    @Html.HiddenFor(model => model.ViewName)
    @Html.HiddenFor(model => model.HistoryTitle)
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div id="loadingText" style="color:#ff0000"><b>yükleniyor...</b></div>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="frmHistory_ModalLabel">@Model.HistoryTitle Tarihçesi </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-responsive">
                            <table id="historyTable" class="table  table-custom">
                                <thead>
                                    <tr>
                                        <th>Versiyon No</th>
                                        <th>Değişen Alan</th>
                                        <th>Yeni Değer</th>
                                        <th>Eski Değer</th>
                                        <th>Kullanıcı Adı</th>
                                        <th>Değişiklik Tarihi</th>
                                    </tr>
                                </thead>
                                @*<tr>
                                <td>2</td>
                                <td>23/12/2017</td>
                                <td>23/06/2018</td>
                                <td>
                                    <p class="durum color-success">Aktif</p>
                                </td>
                                <td class="islem">
                                    <div class="btn-group fr">
                                        <a href="#" class="myIcon icon-primary" data-tooltip="tooltip" data-placement="bottom" title="Görüntüle"><i class="fa fa-search"></i></a>
                                    </div>
                                </td>
                            </tr>*@

                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<script>
    $(".historyDetail").on("click", function () {
        var prevTable = $("#historyTable").DataTable();
        prevTable.destroy();
        $("#loadingText").show();
        var id = $(this).data("id");
        var title = $(this).data("historytitle");

        $("#frmHistory_Modal").find('h4')[0].innerHTML = $("#frmHistory_Modal").find('h4')[0].innerHTML.split('(')[0];
        $("#frmHistory_Modal").find('h4')[0].innerHTML += "(" + title + ")";

        var params = {
            "Id": id,
            "ViewName": $("#ViewName").val(),
            "HistoryTitle": $("#HistoryTitle").text()
        }

        $.get('/Common/HistoryDetail', params, function (data) {

            var _data = JSON.stringify(data.historyList);
            var json = JSON.parse(_data);

            var table = $("#historyTable").DataTable({
                "data": json,
                "bSort": false,
                "columns": [
                    { "data": "VersionNo" },
                    { "data": "ColumnName" },
                    { "data": "NewValue" },
                    { "data": "OldValue" },
                    { "data": "UserName" },
                    { "data": "ChangesDate" }
                ]
            });
            $("#loadingText").hide();
        });
        //en son
        $("#frmHistory_Modal").modal('toggle');
    });
</script>

Presentation/Protein.Web/Views/Shared/Partials/_Import.cshtml
@model  Protein.Web.Models.ImportModel.ImportVM

@using (Html.BeginForm("Import_FileUpload", "AsyncJob", FormMethod.Post, new { id = "ImportModal" }))
{
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.ImportObjectType)
    @Html.HiddenFor(model => model.FormId)
    @Html.HiddenFor(model => model.ShowCompanies)
    @Html.HiddenFor(model => model.SelectedCompanyId)
    <div class="modal" id="modalImport" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">İçeri alınacak dosyayı seç</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                @if (Model.ShowCompanies)
                                {
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <label for="Company" class="control-label"><span class="color-danger">*</span>Sigorta Şirketleri</label>
                                        @*<select tabindex="3" class="chosen-select" id="Companies" name="Companies" title="Seçiniz" required>
                                            <option value=""></option>*@
                                        @Html.DropDownListFor(m => m.SelectedCompany, new SelectList(Model.Companies, "CompanyId", "CompanyName", 0), "Şirket seçiniz", new { @class = "chosen-select" })
                                        @foreach (var Company in Model.Companies)
                                        {
                                            @*<option value="@Company.CompanyId" data-code="@Company.CompanyName">@Company.CompanyName</option>*@
                                        }
                                        @*</select>*@
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <input type="file" class="filestyle" data-buttonText="Dosya seç" data-iconName="fa fa-inbox" id="file" name="file" />
                                </div>
                                <div class="col-md-12">
                                    <div class="btn-wrapper-center">
                                        <button type="submit" id="btnFileUpload" class="btn btn-success btn-sm">Dosyayı Yükle</button>
                                        <button type="button" id="btnCancel" style="display:none;" class="btn btn-danger btn-sm">İptal Et</button>
                                    </div>
                                    <div class="progress progress-striped mt-10">
                                        <div class="progress-bar progress-bar-success">0%</div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group has-feedback">
                                        <div class="col-sm-12">
                                            <div id="result2"></div>
                                            <div id="resultMessage"></div>
                                            <div id="progress"></div>
                                   
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="http://malsup.github.io/min/jquery.form.min.js"></script>
<script>
    var intervalId;
    function updateMonitor(status) {
        $("#result2").html(status);
    }

    $("#btnCancel").click(function () {
        var OK = confirm('İptal etmek istediginizden emin misiniz ? ');
        if (OK) {
            updateMonitor("İşlem iptal edildi");
            $('.progress-bar').width('0%')
            $('.progress-bar').html('0%');
            clearInterval(intervalId);
            $('#btnFileUpload').show();
            $('#btnCancel').hide();
        }
    });


    (function () {

        var bar = $('.progress-bar');
        var percent = $('.progress-bar');
        var status = $('#result2');
        var taskId;
        var isSuccess;

        $('#ImportModal').ajaxForm({
            beforeSend: function () {
                status.empty();
                var percentVal = '0%';
                bar.width(percentVal)
                percent.html(percentVal);
                status.html('Dosya yükleniyor...');
            },
            uploadProgress: function (event, position, total, percentComplete) {
                var percentVal = percentComplete + '%';
                bar.width(percentVal)
                percent.html(percentVal);
            },
            success: function (data) {
                debugger;
                taskId = data.taskId;
                isSuccess = data.IsSuccess;
                var percentVal = '100%';
                bar.width(percentVal)
                percent.html(percentVal);
            },
            complete: function (xhr) {
                debugger;
                var percentVal = '0%';
                bar.width(percentVal)
                percent.html(percentVal);
                status.html('Dosya yüklendi. Lütfen bekleyiniz...');
                debugger;

                if (!isSuccess && isSuccess != null) {
                    var resultJson = JSON.parse(xhr.responseText);
            
                    status.html(resultJson.Message);
                    return;
                } else if (isSuccess == null) {
                    return;
                }

                $("#monitors").append($("<p id='" + taskId + "'/>"));
                updateMonitor("Dosyayı içeri alma işlemi başladı. Lütfen bekleyiniz...");
                $("#btnCancel").show();


                @{
                    // TODO Başarısız işlemler silsilesinde kesmesi lazım... (Yusuf)
                    // Count alıp return...
                }


                    intervalId = setInterval(function () {
                        $.post("/AsyncJob/ImportProgress", { id: taskId }, function (data) {
                            var resultJson = JSON.stringify(data);
                            resultJson = JSON.parse(resultJson);

                            if (resultJson.progress >= 100) {
                                debugger;
                                if (resultJson.errorList != null)
                                    updateMonitor("İşlem tamamlandı <br><br><b>HATALAR:</b><br>" + resultJson.errorList);
                                else updateMonitor("İşlem hatasız tamamlandı");
                                bar.width('100%')
                                percent.html('100%');
                                clearInterval(intervalId);
                                $('#btnFileUpload').show();
                                $('#btnCancel').hide();
                                $('#file').val('');

                                SaveData(resultJson.formId);
                            }

                            else {
                                debugger;
                                if (resultJson.ResultMessage != "") {
                                    updateMonitor(resultJson.ResultMessage + " : " + resultJson.progress + "%");
                                } else {
                                    updateMonitor("Dosya içeriye alınıyor. Lütfen bekleyiniz... " + resultJson.progress + "%");
                                }
                                bar.width(resultJson.progress + '%')
                                percent.html(resultJson.progress + '%');
                                $('#btnFileUpload').hide();
                            }
                        });
                    }, 200);

            },
            afterSend: function (data, status) {
                debugger;
            }
        });

    })();
    //$("#btnFileUpload").click(function () {
    //    var _serialize = $("#ImportModal").serialize();
    //    $.ajax({
    //        url: '/Common/Import_FileUpload',
    //        type: 'POST',
    //        data: _serialize,
    //        dataType: 'json',
    //        success: function (data) {
    //            var response = data;
    //            //window.location = '/Common/Download?fileGuid=' + response.FileGuid
    //            //    + '&filename=' + response.FileName;
    //        },
    //        beforeSend: function () {

    //        },
    //        complete: function () {

    //        }
    //    });
    //});
</script>